import type { CvItem, DecoderProfile } from "./types";
import { nmraBasic } from "./nmra";

const k = "catalog.loksoundV5";

function item(cv: number, extra: Omit<CvItem, "cv">): CvItem {
  return { cv, ...extra };
}

function numbered(
  cvs: number[],
  descriptionKey: string,
  extra: Omit<CvItem, "cv" | "descriptionKey" | "descriptionParams">,
  startN = 1,
): CvItem[] {
  return cvs.map((cv, i) => ({
    cv,
    descriptionKey,
    descriptionParams: { n: startN + i },
    ...extra,
  }));
}

const speedTable: CvItem[] = Array.from({ length: 28 }, (_, i) =>
  item(67 + i, {
    descriptionKey: `${k}.speedTable.description`,
    descriptionParams: { n: i + 1 },
    hintKey: i === 0 || i === 27 ? `${k}.speedTable.hintEnds` : `${k}.speedTable.hint`,
    min: 0,
    max: 255,
    default: i === 0 ? 1 : i === 27 ? 255 : undefined,
  }),
);

const hluDefaults = [42, 85, 127, 170, 212];
const brakeDecelDefaults = [80, 40, 40];
const brakeLimitDefaults = [0, 126, 126];

const loksoundV5Cvs: CvItem[] = [
  item(1, {
    descriptionKey: `${k}.cv1.description`,
    hintKey: `${k}.cv1.hint`,
    min: 1,
    max: 127,
    default: 3,
  }),
  item(2, {
    descriptionKey: `${k}.cv2.description`,
    hintKey: `${k}.cv2.hint`,
    min: 1,
    max: 255,
    default: 3,
  }),
  item(3, {
    descriptionKey: `${k}.cv3.description`,
    hintKey: `${k}.cv3.hint`,
    min: 0,
    max: 255,
    default: 28,
  }),
  item(4, {
    descriptionKey: `${k}.cv4.description`,
    hintKey: `${k}.cv4.hint`,
    min: 0,
    max: 255,
    default: 21,
  }),
  item(5, {
    descriptionKey: `${k}.cv5.description`,
    min: 0,
    max: 255,
    default: 255,
  }),
  item(6, {
    descriptionKey: `${k}.cv6.description`,
    hintKey: `${k}.cv6.hint`,
    min: 0,
    max: 255,
    default: 151,
  }),
  item(7, {
    descriptionKey: `${k}.cv7.description`,
    hintKey: `${k}.cv7.hint`,
    min: 0,
    max: 255,
    readOnly: true,
  }),
  item(8, {
    descriptionKey: `${k}.cv8.description`,
    hintKey: `${k}.cv8.hint`,
    min: 0,
    max: 255,
  }),
  item(9, {
    descriptionKey: `${k}.cv9.description`,
    hintKey: `${k}.cv9.hint`,
    min: 10,
    max: 50,
    default: 40,
  }),
  item(13, {
    descriptionKey: `${k}.cv13.description`,
    hintKey: `${k}.cv13.hint`,
    min: 0,
    max: 255,
    default: 1,
  }),
  item(14, {
    descriptionKey: `${k}.cv14.description`,
    hintKey: `${k}.cv14.hint`,
    min: 0,
    max: 63,
    default: 1,
  }),
  item(15, {
    descriptionKey: `${k}.cv15.description`,
    hintKey: `${k}.cv15.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(16, {
    descriptionKey: `${k}.cv16.description`,
    hintKey: `${k}.cv16.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(17, {
    descriptionKey: `${k}.cv17.description`,
    hintKey: `${k}.cv17.hint`,
    min: 0,
    max: 255,
    default: 192,
  }),
  item(18, {
    descriptionKey: `${k}.cv18.description`,
    min: 0,
    max: 255,
    default: 3,
  }),
  item(19, {
    descriptionKey: `${k}.cv19.description`,
    hintKey: `${k}.cv19.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(21, {
    descriptionKey: `${k}.cv21.description`,
    hintKey: `${k}.cv21.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(22, {
    descriptionKey: `${k}.cv22.description`,
    hintKey: `${k}.cv22.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(23, {
    descriptionKey: `${k}.cv23.description`,
    hintKey: `${k}.cv23.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(24, {
    descriptionKey: `${k}.cv24.description`,
    hintKey: `${k}.cv24.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(27, {
    descriptionKey: `${k}.cv27.description`,
    hintKey: `${k}.cv27.hint`,
    kind: "bits",
    default: 28,
    bits: [
      { bit: 0, offKey: `${k}.cv27.b0.off`, onKey: `${k}.cv27.b0.on` },
      { bit: 1, offKey: `${k}.cv27.b1.off`, onKey: `${k}.cv27.b1.on` },
      { bit: 2, offKey: `${k}.cv27.b2.off`, onKey: `${k}.cv27.b2.on` },
      { bit: 3, offKey: `${k}.cv27.b3.off`, onKey: `${k}.cv27.b3.on` },
      { bit: 4, offKey: `${k}.cv27.b4.off`, onKey: `${k}.cv27.b4.on` },
      { bit: 5, offKey: `${k}.cv27.b5.off`, onKey: `${k}.cv27.b5.on` },
      { bit: 6, offKey: `${k}.cv27.b6.off`, onKey: `${k}.cv27.b6.on` },
      { bit: 7, offKey: `${k}.cv27.b7.off`, onKey: `${k}.cv27.b7.on` },
    ],
  }),
  item(28, {
    descriptionKey: `${k}.cv28.description`,
    hintKey: `${k}.cv28.hint`,
    kind: "bits",
    bits: [
      { bit: 0, offKey: `${k}.cv28.b0.off`, onKey: `${k}.cv28.b0.on` },
      { bit: 1, offKey: `${k}.cv28.b1.off`, onKey: `${k}.cv28.b1.on` },
      { bit: 7, offKey: `${k}.cv28.b7.off`, onKey: `${k}.cv28.b7.on` },
    ],
  }),
  item(29, {
    descriptionKey: `${k}.cv29.description`,
    hintKey: `${k}.cv29.hint`,
    kind: "bits",
    default: 12,
    bits: [
      { bit: 0, offKey: `${k}.cv29.b0.off`, onKey: `${k}.cv29.b0.on` },
      { bit: 1, offKey: `${k}.cv29.b1.off`, onKey: `${k}.cv29.b1.on` },
      { bit: 2, offKey: `${k}.cv29.b2.off`, onKey: `${k}.cv29.b2.on` },
      { bit: 3, offKey: `${k}.cv29.b3.off`, onKey: `${k}.cv29.b3.on` },
      { bit: 4, offKey: `${k}.cv29.b4.off`, onKey: `${k}.cv29.b4.on` },
      { bit: 5, offKey: `${k}.cv29.b5.off`, onKey: `${k}.cv29.b5.on` },
    ],
  }),
  item(31, {
    descriptionKey: `${k}.cv31.description`,
    hintKey: `${k}.cv31.hint`,
    min: 0,
    max: 16,
    default: 16,
  }),
  item(32, {
    descriptionKey: `${k}.cv32.description`,
    hintKey: `${k}.cv32.hint`,
    min: 0,
    max: 16,
    default: 0,
  }),
  item(47, {
    descriptionKey: `${k}.cv47.description`,
    hintKey: `${k}.cv47.hint`,
    kind: "bits",
    default: 15,
    bits: [
      { bit: 0, offKey: `${k}.cv47.b0.off`, onKey: `${k}.cv47.b0.on` },
      { bit: 1, offKey: `${k}.cv47.b1.off`, onKey: `${k}.cv47.b1.on` },
      { bit: 2, offKey: `${k}.cv47.b2.off`, onKey: `${k}.cv47.b2.on` },
      { bit: 3, offKey: `${k}.cv47.b3.off`, onKey: `${k}.cv47.b3.on` },
    ],
  }),
  item(49, {
    descriptionKey: `${k}.cv49.description`,
    hintKey: `${k}.cv49.hint`,
    kind: "bits",
    default: 19,
    bits: [
      { bit: 0, offKey: `${k}.cv49.b0.off`, onKey: `${k}.cv49.b0.on` },
      { bit: 3, offKey: `${k}.cv49.b3.off`, onKey: `${k}.cv49.b3.on` },
      { bit: 4, offKey: `${k}.cv49.b4.off`, onKey: `${k}.cv49.b4.on` },
      { bit: 5, offKey: `${k}.cv49.b5.off`, onKey: `${k}.cv49.b5.on` },
      { bit: 7, offKey: `${k}.cv49.b7.off`, onKey: `${k}.cv49.b7.on` },
    ],
  }),
  item(50, {
    descriptionKey: `${k}.cv50.description`,
    hintKey: `${k}.cv50.hint`,
    kind: "bits",
    default: 3,
    bits: [
      { bit: 0, offKey: `${k}.cv50.b0.off`, onKey: `${k}.cv50.b0.on` },
      { bit: 1, offKey: `${k}.cv50.b1.off`, onKey: `${k}.cv50.b1.on` },
    ],
  }),
  item(51, {
    descriptionKey: `${k}.cv51.description`,
    min: 0,
    max: 255,
    default: 10,
  }),
  item(52, {
    descriptionKey: `${k}.cv52.description`,
    min: 0,
    max: 255,
    default: 10,
  }),
  item(53, {
    descriptionKey: `${k}.cv53.description`,
    hintKey: `${k}.cv53.hint`,
    min: 0,
    max: 255,
    default: 130,
  }),
  item(54, {
    descriptionKey: `${k}.cv54.description`,
    min: 0,
    max: 255,
    default: 50,
  }),
  item(55, {
    descriptionKey: `${k}.cv55.description`,
    min: 0,
    max: 255,
    default: 100,
  }),
  item(56, {
    descriptionKey: `${k}.cv56.description`,
    hintKey: `${k}.cv56.hint`,
    min: 1,
    max: 255,
    default: 255,
  }),
  item(57, {
    descriptionKey: `${k}.cv57.description`,
    min: 1,
    max: 255,
    default: 30,
  }),
  item(58, {
    descriptionKey: `${k}.cv58.description`,
    min: 1,
    max: 255,
    default: 20,
  }),
  item(63, {
    descriptionKey: `${k}.cv63.description`,
    hintKey: `${k}.cv63.hint`,
    min: 0,
    max: 192,
    default: 128,
  }),
  item(64, {
    descriptionKey: `${k}.cv64.description`,
    hintKey: `${k}.cv64.hint`,
    min: 0,
    max: 255,
    default: 60,
  }),
  item(65, {
    descriptionKey: `${k}.cv65.description`,
    min: 0,
    max: 255,
    default: 7,
  }),
  item(66, {
    descriptionKey: `${k}.cv66.description`,
    hintKey: `${k}.cv66.hint`,
    min: 0,
    max: 255,
    default: 128,
  }),
  ...speedTable,
  item(95, {
    descriptionKey: `${k}.cv95.description`,
    hintKey: `${k}.cv95.hint`,
    min: 0,
    max: 255,
    default: 128,
  }),
  item(96, {
    descriptionKey: `${k}.cv96.description`,
    hintKey: `${k}.cv96.hint`,
    min: 0,
    max: 9,
  }),
  item(97, {
    descriptionKey: `${k}.cv97.description`,
    hintKey: `${k}.cv97.hint`,
    min: 0,
    max: 99,
  }),
  item(98, {
    descriptionKey: `${k}.cv98.description`,
    hintKey: `${k}.cv98.hint`,
    min: 0,
    max: 9,
  }),
  item(99, {
    descriptionKey: `${k}.cv99.description`,
    hintKey: `${k}.cv99.hint`,
    min: 0,
    max: 255,
  }),
  item(101, {
    descriptionKey: `${k}.cv101.description`,
    hintKey: `${k}.cv101.hint`,
    min: 0,
    max: 128,
    default: 64,
  }),
  item(102, {
    descriptionKey: `${k}.cv102.description`,
    hintKey: `${k}.cv102.hint`,
    min: 0,
    max: 255,
    default: 12,
  }),
  item(103, {
    descriptionKey: `${k}.cv103.description`,
    hintKey: `${k}.cv103.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(104, {
    descriptionKey: `${k}.cv104.description`,
    hintKey: `${k}.cv104.hint`,
    min: 0,
    max: 255,
    default: 255,
  }),
  item(105, {
    descriptionKey: `${k}.cv105.description`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(106, {
    descriptionKey: `${k}.cv106.description`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(111, {
    descriptionKey: `${k}.cv111.description`,
    hintKey: `${k}.cv111.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(112, {
    descriptionKey: `${k}.cv112.description`,
    hintKey: `${k}.cv112.hint`,
    min: 0,
    max: 255,
    default: 32,
  }),
  item(113, {
    descriptionKey: `${k}.cv113.description`,
    hintKey: `${k}.cv113.hint`,
    min: 0,
    max: 255,
  }),
  item(116, {
    descriptionKey: `${k}.cv116.description`,
    hintKey: `${k}.cv116.hint`,
    min: 50,
    max: 200,
    default: 50,
  }),
  item(117, {
    descriptionKey: `${k}.cv117.description`,
    hintKey: `${k}.cv117.hint`,
    min: 50,
    max: 200,
    default: 150,
  }),
  item(118, {
    descriptionKey: `${k}.cv118.description`,
    hintKey: `${k}.cv118.hint`,
    min: 10,
    max: 20,
    default: 15,
  }),
  item(119, {
    descriptionKey: `${k}.cv119.description`,
    hintKey: `${k}.cv119.hint`,
    min: 0,
    max: 255,
    default: 100,
  }),
  item(123, {
    descriptionKey: `${k}.cv123.description`,
    min: 0,
    max: 255,
    default: 15,
  }),
  item(124, {
    descriptionKey: `${k}.cv124.description`,
    hintKey: `${k}.cv124.hint`,
    kind: "bits",
    default: 21,
    bits: [
      { bit: 0, offKey: `${k}.cv124.b0.off`, onKey: `${k}.cv124.b0.on` },
      { bit: 1, offKey: `${k}.cv124.b1.off`, onKey: `${k}.cv124.b1.on` },
      { bit: 2, offKey: `${k}.cv124.b2.off`, onKey: `${k}.cv124.b2.on` },
      { bit: 3, offKey: `${k}.cv124.b3.off`, onKey: `${k}.cv124.b3.on` },
      { bit: 4, offKey: `${k}.cv124.b4.off`, onKey: `${k}.cv124.b4.on` },
      { bit: 5, offKey: `${k}.cv124.b5.off`, onKey: `${k}.cv124.b5.on` },
      { bit: 6, offKey: `${k}.cv124.b6.off`, onKey: `${k}.cv124.b6.on` },
    ],
  }),
  item(125, {
    descriptionKey: `${k}.cv125.description`,
    min: 0,
    max: 255,
    default: 90,
  }),
  item(126, {
    descriptionKey: `${k}.cv126.description`,
    min: 0,
    max: 255,
    default: 130,
  }),
  item(127, {
    descriptionKey: `${k}.cv127.description`,
    min: 0,
    max: 255,
    default: 90,
  }),
  item(128, {
    descriptionKey: `${k}.cv128.description`,
    min: 0,
    max: 255,
    default: 130,
  }),
  item(129, {
    descriptionKey: `${k}.cv129.description`,
    hintKey: `${k}.cv129.hint`,
    min: 0,
    max: 255,
    default: 15,
  }),
  item(130, {
    descriptionKey: `${k}.cv130.description`,
    hintKey: `${k}.cv130.hint`,
    min: 0,
    max: 255,
    default: 5,
  }),
  item(132, {
    descriptionKey: `${k}.cv132.description`,
    hintKey: `${k}.cv132.hint`,
    min: 0,
    max: 255,
    default: 80,
  }),
  item(133, {
    descriptionKey: `${k}.cv133.description`,
    hintKey: `${k}.cv133.hint`,
    min: 0,
    max: 255,
    default: 128,
  }),
  item(134, {
    descriptionKey: `${k}.cv134.description`,
    hintKey: `${k}.cv134.hint`,
    min: 4,
    max: 32,
    default: 10,
  }),
  item(138, {
    descriptionKey: `${k}.cv138.description`,
    hintKey: `${k}.cv138.hint`,
    min: 0,
    max: 255,
    default: 128,
  }),
  item(139, {
    descriptionKey: `${k}.cv139.description`,
    hintKey: `${k}.cv139.hint`,
    min: 0,
    max: 255,
    default: 128,
  }),
  item(140, {
    descriptionKey: `${k}.cv140.description`,
    min: 0,
    max: 255,
    default: 255,
  }),
  item(141, {
    descriptionKey: `${k}.cv141.description`,
    hintKey: `${k}.cv141.hint`,
    min: 0,
    max: 255,
    default: 10,
  }),
  item(142, {
    descriptionKey: `${k}.cv142.description`,
    hintKey: `${k}.cv142.hint`,
    min: 0,
    max: 255,
    default: 125,
  }),
  item(143, {
    descriptionKey: `${k}.cv143.description`,
    hintKey: `${k}.cv143.hint`,
    min: 0,
    max: 255,
    default: 100,
  }),
  item(144, {
    descriptionKey: `${k}.cv144.description`,
    hintKey: `${k}.cv144.hint`,
    min: 0,
    max: 255,
    default: 150,
  }),
  item(149, {
    descriptionKey: `${k}.cv149.description`,
    hintKey: `${k}.cv149.hint`,
    min: 0,
    max: 255,
    default: 255,
  }),
  ...hluDefaults.map((def, i) =>
    item(150 + i, {
      descriptionKey: `${k}.hlu.description`,
      descriptionParams: { n: i + 1 },
      min: 0,
      max: 255,
      default: def,
    }),
  ),
  ...numbered(
    Array.from({ length: 16 }, (_, i) => 155 + i),
    `${k}.soundCv.description`,
    { hintKey: `${k}.soundCv.hint`, min: 0, max: 255, default: 0 },
  ),
  ...brakeDecelDefaults.map((def, i) =>
    item(179 + i, {
      descriptionKey: `${k}.brakeDecel.description`,
      descriptionParams: { n: i + 1 },
      hintKey: `${k}.brakeDecel.hint`,
      min: 0,
      max: 255,
      default: def,
    }),
  ),
  ...brakeLimitDefaults.map((def, i) =>
    item(182 + i, {
      descriptionKey: `${k}.brakeLimit.description`,
      descriptionParams: { n: i + 1 },
      hintKey: `${k}.brakeLimit.hint`,
      min: 0,
      max: 126,
      default: def,
    }),
  ),
  item(246, {
    descriptionKey: `${k}.cv246.description`,
    hintKey: `${k}.cv246.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(247, {
    descriptionKey: `${k}.cv247.description`,
    hintKey: `${k}.cv247.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(248, {
    descriptionKey: `${k}.cv248.description`,
    hintKey: `${k}.cv248.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(249, {
    descriptionKey: `${k}.cv249.description`,
    hintKey: `${k}.cv249.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(250, {
    descriptionKey: `${k}.cv250.description`,
    hintKey: `${k}.cv250.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(253, {
    descriptionKey: `${k}.cv253.description`,
    hintKey: `${k}.cv253.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(254, {
    descriptionKey: `${k}.cv254.description`,
    hintKey: `${k}.cv254.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(255, {
    descriptionKey: `${k}.cv255.description`,
    hintKey: `${k}.cv255.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
];

export const loksoundV5: DecoderProfile = {
  id: "loksound-v5",
  features: ["cv", "speed", "address", "volume", "mapping", "coupler"],
  cvs: [...loksoundV5Cvs].sort((a, b) => a.cv - b.cv),
  writePriority: [
    [29],
    [2, 5, 6],
  ],
};

export const loksoundV4: DecoderProfile = {
  id: "loksound-v4",
  features: ["cv", "speed", "address", "volume", "mapping", "coupler"],
  cvs: [
    ...nmraBasic,
    {
      cv: 63,
      descriptionKey: "catalog.loksoundV4.cv63.description",
      hintKey: "catalog.loksoundV4.cv63.hint",
      min: 0,
      max: 64,
      default: 64,
    },
    {
      cv: 49,
      descriptionKey: "catalog.loksoundV4.cv49.description",
      min: 0,
      max: 255,
    },
    {
      cv: 246,
      descriptionKey: "catalog.loksoundV4.cv246.description",
      hintKey: "catalog.loksoundV4.cv246.hint",
      min: 0,
      max: 255,
      default: 0,
    },
    {
      cv: 247,
      descriptionKey: "catalog.loksoundV4.cv247.description",
      hintKey: "catalog.loksoundV4.cv247.hint",
      min: 0,
      max: 255,
      default: 0,
    },
    {
      cv: 248,
      descriptionKey: "catalog.loksoundV4.cv248.description",
      hintKey: "catalog.loksoundV4.cv248.hint",
      min: 0,
      max: 255,
      default: 0,
    },
  ],
};
