import { grouped, type CvItem, type DecoderProfile } from "./types";

const k = "catalog.zimoMs450";

function item(cv: number, extra: Omit<CvItem, "cv">): CvItem {
  return { cv, ...extra };
}

function numbered(
  cvs: number[],
  descriptionKey: string,
  extra: Omit<CvItem, "cv" | "descriptionKey" | "descriptionParams">,
  startN = 1,
): CvItem[] {
  return cvs.map((cv, i) => ({
    cv,
    descriptionKey,
    descriptionParams: { n: startN + i },
    ...extra,
  }));
}

/** Effect CVs: bits 7–2 = code, bits 1–0 = direction (00 both, 01 fwd, 10 rev). */
const EFFECT_CODES = [
  0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 20, 22, 23, 24, 26, 27, 28,
];

function lightingEffectValues(): number[] {
  const extras = [76, 116, 120, 124, 128, 132, 135];
  const out = new Set<number>(extras);
  for (const code of EFFECT_CODES) {
    const base = code << 2;
    out.add(base);
    out.add(base + 1);
    out.add(base + 2);
  }
  return [...out].filter((v) => v <= 255).sort((a, b) => a - b);
}

const LIGHTING_EFFECTS = lightingEffectValues();

const effectExtra: Omit<CvItem, "cv" | "descriptionKey" | "descriptionParams"> = {
  hintKey: `${k}.effect.hint`,
  min: 0,
  max: 255,
  default: 0,
  allowedValues: LIGHTING_EFFECTS,
};

const speedTable: CvItem[] = Array.from({ length: 28 }, (_, i) =>
  item(67 + i, {
    descriptionKey: `${k}.speedTable.description`,
    descriptionParams: { n: i + 1 },
    hintKey: `${k}.speedTable.hint`,
    min: 0,
    max: 255,
  }),
);

const mapF1to12Defaults = [4, 8, 2, 4, 8, 16, 4, 8, 16, 32, 64, 128];
const hluDefaults = [20, 40, 70, 110, 180];

function fSoundTriple(f: number, sampleCv: number): CvItem[] {
  const params = { n: f };
  return [
    item(sampleCv, {
      descriptionKey: `${k}.functionSoundSample.description`,
      descriptionParams: params,
      hintKey: `${k}.functionSoundSample.hint`,
      min: 0,
      max: 255,
    }),
    item(sampleCv + 1, {
      descriptionKey: `${k}.functionSoundVol.description`,
      descriptionParams: params,
      hintKey: `${k}.functionSoundVol.hint`,
      min: 0,
      max: 255,
      default: 0,
    }),
    item(sampleCv + 2, {
      descriptionKey: `${k}.functionSoundLoop.description`,
      descriptionParams: params,
      hintKey: `${k}.functionSoundLoop.hint`,
      min: 0,
      max: 255,
    }),
  ];
}

const functionSounds: CvItem[] = [
  ...fSoundTriple(0, 570),
  ...Array.from({ length: 19 }, (_, i) => fSoundTriple(i + 1, 513 + i * 3)).flat(),
  ...Array.from({ length: 9 }, (_, i) => fSoundTriple(20 + i, 673 + i * 3)).flat(),
];

function swissGroup(group: number, start: number): CvItem[] {
  const roles = ["f", "m", "a1f", "a2f", "a1r", "a2r"] as const;
  return roles.map((role, i) =>
    item(start + i, {
      descriptionKey: `${k}.swiss.${role}`,
      descriptionParams: { n: group },
      hintKey: `${k}.swiss.hint`,
      min: 0,
      max: 255,
      default: 0,
    }),
  );
}

const swissMapping: CvItem[] = [
  ...Array.from({ length: 13 }, (_, i) => swissGroup(i + 1, 430 + i * 6)).flat(),
  ...Array.from({ length: 4 }, (_, i) => swissGroup(14 + i, 800 + i * 6)).flat(),
];

function servoN(n: number, start: number): CvItem[] {
  const roles = ["left", "right", "center", "speed"] as const;
  const defaults = [49, 205, 127, 30];
  return roles.map((role, i) =>
    item(start + i, {
      descriptionKey: `${k}.servo.${role}`,
      descriptionParams: { n },
      hintKey: `${k}.servo.${role}Hint`,
      min: 0,
      max: 255,
      default: defaults[i],
    }),
  );
}

function randomInterval(z: number, start: number, defaults: [number, number, number]): CvItem[] {
  const roles = ["min", "max", "duration"] as const;
  return roles.map((role, i) =>
    item(start + i, {
      descriptionKey: `${k}.random.${role}`,
      descriptionParams: { n: z },
      hintKey: `${k}.random.${role}Hint`,
      min: 0,
      max: 255,
      default: defaults[i],
    }),
  );
}

function randomSound(z: number, start: number): CvItem[] {
  return [
    item(start, {
      descriptionKey: `${k}.random.sample`,
      descriptionParams: { n: z },
      hintKey: `${k}.random.sampleHint`,
      min: 0,
      max: 255,
    }),
    item(start + 1, {
      descriptionKey: `${k}.random.vol`,
      descriptionParams: { n: z },
      hintKey: `${k}.random.volHint`,
      min: 0,
      max: 255,
    }),
    item(start + 2, {
      descriptionKey: `${k}.random.loop`,
      descriptionParams: { n: z },
      hintKey: `${k}.random.loopHint`,
      min: 0,
      max: 255,
    }),
  ];
}

const zimoMs450Cvs: CvItem[] = [
  item(1, {
    descriptionKey: `${k}.cv1.description`,
    hintKey: `${k}.cv1.hint`,
    min: 1,
    max: 127,
    default: 3,
  }),
  item(2, {
    descriptionKey: `${k}.cv2.description`,
    hintKey: `${k}.cv2.hint`,
    min: 1,
    max: 255,
    default: 1,
  }),
  item(3, {
    descriptionKey: `${k}.cv3.description`,
    hintKey: `${k}.cv3.hint`,
    min: 0,
    max: 255,
    default: 2,
  }),
  item(4, {
    descriptionKey: `${k}.cv4.description`,
    hintKey: `${k}.cv4.hint`,
    min: 0,
    max: 255,
    default: 1,
  }),
  item(5, {
    descriptionKey: `${k}.cv5.description`,
    hintKey: `${k}.cv5.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(6, {
    descriptionKey: `${k}.cv6.description`,
    hintKey: `${k}.cv6.hint`,
    min: 1,
    max: 255,
    default: 1,
  }),
  item(7, {
    descriptionKey: `${k}.cv7.description`,
    hintKey: `${k}.cv7.hint`,
    min: 0,
    max: 255,
    readOnly: true,
  }),
  item(8, {
    descriptionKey: `${k}.cv8.description`,
    hintKey: `${k}.cv8.hint`,
    min: 0,
    max: 255,
  }),
  item(9, {
    descriptionKey: `${k}.cv9.description`,
    hintKey: `${k}.cv9.hint`,
    min: 0,
    max: 199,
    default: 55,
  }),
  item(10, {
    descriptionKey: `${k}.cv10.description`,
    hintKey: `${k}.cv10.hint`,
    min: 0,
    max: 3,
    default: 0,
  }),
  item(12, {
    descriptionKey: `${k}.cv12.description`,
    hintKey: `${k}.cv12.hint`,
    kind: "bits",
    bits: [
      { bit: 0, offKey: `${k}.cv12.b0.off`, onKey: `${k}.cv12.b0.on` },
      { bit: 4, offKey: `${k}.cv12.b4.off`, onKey: `${k}.cv12.b4.on` },
      { bit: 5, offKey: `${k}.cv12.b5.off`, onKey: `${k}.cv12.b5.on` },
      { bit: 6, offKey: `${k}.cv12.b6.off`, onKey: `${k}.cv12.b6.on` },
    ],
  }),
  item(13, {
    descriptionKey: `${k}.cv13.description`,
    hintKey: `${k}.cv13.hint`,
    min: 0,
    max: 255,
    default: 67,
  }),
  item(14, {
    descriptionKey: `${k}.cv14.description`,
    hintKey: `${k}.cv14.hint`,
    kind: "bits",
    default: 67,
    bits: [
      { bit: 0, offKey: `${k}.cv14.b0.off`, onKey: `${k}.cv14.b0.on` },
      { bit: 1, offKey: `${k}.cv14.b1.off`, onKey: `${k}.cv14.b1.on` },
      { bit: 2, offKey: `${k}.cv14.b2.off`, onKey: `${k}.cv14.b2.on` },
      { bit: 3, offKey: `${k}.cv14.b3.off`, onKey: `${k}.cv14.b3.on` },
      { bit: 4, offKey: `${k}.cv14.b4.off`, onKey: `${k}.cv14.b4.on` },
      { bit: 5, offKey: `${k}.cv14.b5.off`, onKey: `${k}.cv14.b5.on` },
      { bit: 6, offKey: `${k}.cv14.b6.off`, onKey: `${k}.cv14.b6.on` },
    ],
  }),
  item(15, {
    descriptionKey: `${k}.cv15.description`,
    hintKey: `${k}.cv15.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(16, {
    descriptionKey: `${k}.cv16.description`,
    hintKey: `${k}.cv16.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(17, {
    descriptionKey: `${k}.cv17.description`,
    hintKey: `${k}.cv17.hint`,
    min: 0,
    max: 255,
    default: 192,
  }),
  item(18, {
    descriptionKey: `${k}.cv18.description`,
    min: 0,
    max: 255,
    default: 128,
  }),
  item(19, {
    descriptionKey: `${k}.cv19.description`,
    hintKey: `${k}.cv19.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(20, {
    descriptionKey: `${k}.cv20.description`,
    hintKey: `${k}.cv20.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(21, {
    descriptionKey: `${k}.cv21.description`,
    hintKey: `${k}.cv21.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(22, {
    descriptionKey: `${k}.cv22.description`,
    hintKey: `${k}.cv22.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(23, {
    descriptionKey: `${k}.cv23.description`,
    hintKey: `${k}.cv23.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(24, {
    descriptionKey: `${k}.cv24.description`,
    hintKey: `${k}.cv24.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(27, {
    descriptionKey: `${k}.cv27.description`,
    hintKey: `${k}.cv27.hint`,
    kind: "bits",
    bits: [
      { bit: 0, offKey: `${k}.cv27.b0.off`, onKey: `${k}.cv27.b0.on` },
      { bit: 1, offKey: `${k}.cv27.b1.off`, onKey: `${k}.cv27.b1.on` },
    ],
  }),
  item(28, {
    descriptionKey: `${k}.cv28.description`,
    hintKey: `${k}.cv28.hint`,
    kind: "bits",
    default: 131,
    bits: [
      { bit: 0, offKey: `${k}.cv28.b0.off`, onKey: `${k}.cv28.b0.on` },
      { bit: 1, offKey: `${k}.cv28.b1.off`, onKey: `${k}.cv28.b1.on` },
      { bit: 6, offKey: `${k}.cv28.b6.off`, onKey: `${k}.cv28.b6.on` },
      { bit: 7, offKey: `${k}.cv28.b7.off`, onKey: `${k}.cv28.b7.on` },
    ],
  }),
  item(29, {
    descriptionKey: `${k}.cv29.description`,
    hintKey: `${k}.cv29.hint`,
    kind: "bits",
    default: 14,
    bits: [
      { bit: 0, offKey: `${k}.cv29.b0.off`, onKey: `${k}.cv29.b0.on` },
      { bit: 1, offKey: `${k}.cv29.b1.off`, onKey: `${k}.cv29.b1.on` },
      { bit: 2, offKey: `${k}.cv29.b2.off`, onKey: `${k}.cv29.b2.on` },
      { bit: 3, offKey: `${k}.cv29.b3.off`, onKey: `${k}.cv29.b3.on` },
      { bit: 4, offKey: `${k}.cv29.b4.off`, onKey: `${k}.cv29.b4.on` },
      { bit: 5, offKey: `${k}.cv29.b5.off`, onKey: `${k}.cv29.b5.on` },
    ],
  }),
  item(30, {
    descriptionKey: `${k}.cv30.description`,
    hintKey: `${k}.cv30.hint`,
    min: 0,
    max: 255,
    default: 1,
  }),
  item(33, {
    descriptionKey: `${k}.cv33.description`,
    hintKey: `${k}.mapFn.hint`,
    min: 0,
    max: 255,
    default: 1,
  }),
  item(34, {
    descriptionKey: `${k}.cv34.description`,
    hintKey: `${k}.mapFn.hint`,
    min: 0,
    max: 255,
    default: 2,
  }),
  ...mapF1to12Defaults.map((def, i) =>
    item(35 + i, {
      descriptionKey: `${k}.mapFn.description`,
      descriptionParams: { n: i + 1 },
      hintKey: `${k}.mapFn.hint`,
      min: 0,
      max: 255,
      default: def,
    }),
  ),
  item(49, {
    descriptionKey: `${k}.cv49.description`,
    hintKey: `${k}.cv49.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(50, {
    descriptionKey: `${k}.cv50.description`,
    hintKey: `${k}.cv50.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  ...hluDefaults.map((def, i) =>
    item(51 + i, {
      descriptionKey: `${k}.hlu.description`,
      descriptionParams: { n: i + 1 },
      hintKey: `${k}.hlu.hint`,
      min: 0,
      max: 255,
      default: def,
    }),
  ),
  item(56, {
    descriptionKey: `${k}.cv56.description`,
    hintKey: `${k}.cv56.hint`,
    min: 0,
    max: 99,
    default: 55,
  }),
  item(57, {
    descriptionKey: `${k}.cv57.description`,
    hintKey: `${k}.cv57.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(58, {
    descriptionKey: `${k}.cv58.description`,
    hintKey: `${k}.cv58.hint`,
    min: 0,
    max: 255,
    default: 255,
  }),
  item(59, {
    descriptionKey: `${k}.cv59.description`,
    hintKey: `${k}.cv59.hint`,
    min: 0,
    max: 255,
    default: 5,
  }),
  item(60, {
    descriptionKey: `${k}.cv60.description`,
    hintKey: `${k}.cv60.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(61, {
    descriptionKey: `${k}.cv61.description`,
    hintKey: `${k}.cv61.hint`,
    kind: "enum",
    default: 0,
    options: [
      { value: 0, labelKey: `${k}.cv61.leftShift` },
      { value: 97, labelKey: `${k}.cv61.noLeftShift` },
    ],
  }),
  item(62, {
    descriptionKey: `${k}.cv62.description`,
    hintKey: `${k}.cv62.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(63, {
    descriptionKey: `${k}.cv63.description`,
    hintKey: `${k}.cv63.hint`,
    min: 0,
    max: 99,
    default: 51,
  }),
  item(64, {
    descriptionKey: `${k}.cv64.description`,
    hintKey: `${k}.cv64.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(65, {
    descriptionKey: `${k}.cv65.description`,
    hintKey: `${k}.cv65.hint`,
    min: 0,
    max: 255,
    readOnly: true,
  }),
  item(66, {
    descriptionKey: `${k}.cv66.description`,
    hintKey: `${k}.cv66.hint`,
    min: 0,
    max: 127,
    default: 0,
  }),
  ...speedTable,
  item(95, {
    descriptionKey: `${k}.cv95.description`,
    hintKey: `${k}.cv95.hint`,
    min: 0,
    max: 127,
    default: 0,
  }),
  item(97, {
    descriptionKey: `${k}.cv97.description`,
    hintKey: `${k}.cv97.hint`,
    min: 0,
    max: 28,
    default: 0,
  }),
  item(99, {
    descriptionKey: `${k}.cv99.description`,
    hintKey: `${k}.cv99.hint`,
    kind: "bits",
    bits: [
      { bit: 0, offKey: `${k}.cv99.b0.off`, onKey: `${k}.cv99.b0.on` },
      { bit: 1, offKey: `${k}.cv99.b1.off`, onKey: `${k}.cv99.b1.on` },
      { bit: 2, offKey: `${k}.cv99.b2.off`, onKey: `${k}.cv99.b2.on` },
    ],
  }),
  item(100, {
    descriptionKey: `${k}.cv100.description`,
    hintKey: `${k}.cv100.hint`,
    min: 0,
    max: 255,
    readOnly: true,
  }),
  item(101, {
    descriptionKey: `${k}.cv101.description`,
    hintKey: `${k}.cv101.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(106, {
    descriptionKey: `${k}.cv106.description`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(107, {
    descriptionKey: `${k}.cv107.description`,
    hintKey: `${k}.cv107.hint`,
    min: 0,
    max: 220,
    default: 0,
  }),
  item(108, {
    descriptionKey: `${k}.cv108.description`,
    hintKey: `${k}.cv108.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(109, {
    descriptionKey: `${k}.cv109.description`,
    hintKey: `${k}.cv109.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(110, {
    descriptionKey: `${k}.cv110.description`,
    hintKey: `${k}.cv110.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(111, {
    descriptionKey: `${k}.cv111.description`,
    hintKey: `${k}.cv111.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(112, {
    descriptionKey: `${k}.cv112.description`,
    hintKey: `${k}.cv112.hint`,
    kind: "bits",
    default: 4,
    bits: [{ bit: 2, offKey: `${k}.cv112.b2.off`, onKey: `${k}.cv112.b2.on` }],
  }),
  item(114, {
    descriptionKey: `${k}.cv114.description`,
    hintKey: `${k}.cv114.hint`,
    kind: "bits",
    default: 0,
    bits: [
      { bit: 0, offKey: `${k}.cv114.b0.off`, onKey: `${k}.cv114.b0.on` },
      { bit: 1, offKey: `${k}.cv114.b1.off`, onKey: `${k}.cv114.b1.on` },
      { bit: 2, offKey: `${k}.cv114.b2.off`, onKey: `${k}.cv114.b2.on` },
      { bit: 3, offKey: `${k}.cv114.b3.off`, onKey: `${k}.cv114.b3.on` },
      { bit: 4, offKey: `${k}.cv114.b4.off`, onKey: `${k}.cv114.b4.on` },
      { bit: 5, offKey: `${k}.cv114.b5.off`, onKey: `${k}.cv114.b5.on` },
      { bit: 6, offKey: `${k}.cv114.b6.off`, onKey: `${k}.cv114.b6.on` },
      { bit: 7, offKey: `${k}.cv114.b7.off`, onKey: `${k}.cv114.b7.on` },
    ],
  }),
  item(115, {
    descriptionKey: `${k}.cv115.description`,
    hintKey: `${k}.cv115.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(116, {
    descriptionKey: `${k}.cv116.description`,
    hintKey: `${k}.cv116.hint`,
    min: 0,
    max: 199,
    default: 0,
  }),
  item(117, {
    descriptionKey: `${k}.cv117.description`,
    hintKey: `${k}.cv117.hint`,
    min: 0,
    max: 99,
    default: 0,
  }),
  item(118, {
    descriptionKey: `${k}.cv118.description`,
    hintKey: `${k}.cv118.hint`,
    kind: "bits",
    default: 0,
    bits: [
      { bit: 0, offKey: `${k}.cv118.b0.off`, onKey: `${k}.cv118.b0.on` },
      { bit: 1, offKey: `${k}.cv118.b1.off`, onKey: `${k}.cv118.b1.on` },
      { bit: 2, offKey: `${k}.cv118.b2.off`, onKey: `${k}.cv118.b2.on` },
      { bit: 3, offKey: `${k}.cv118.b3.off`, onKey: `${k}.cv118.b3.on` },
      { bit: 4, offKey: `${k}.cv118.b4.off`, onKey: `${k}.cv118.b4.on` },
      { bit: 5, offKey: `${k}.cv118.b5.off`, onKey: `${k}.cv118.b5.on` },
      { bit: 6, offKey: `${k}.cv118.b6.off`, onKey: `${k}.cv118.b6.on` },
      { bit: 7, offKey: `${k}.cv118.b7.off`, onKey: `${k}.cv118.b7.on` },
    ],
  }),
  item(119, {
    descriptionKey: `${k}.cv119.description`,
    hintKey: `${k}.cv119.hint`,
    kind: "bits",
    default: 0,
    bits: [
      { bit: 0, offKey: `${k}.beam.b0.off`, onKey: `${k}.beam.b0.on` },
      { bit: 1, offKey: `${k}.beam.b1.off`, onKey: `${k}.beam.b1.on` },
      { bit: 2, offKey: `${k}.beam.b2.off`, onKey: `${k}.beam.b2.on` },
      { bit: 3, offKey: `${k}.beam.b3.off`, onKey: `${k}.beam.b3.on` },
      { bit: 4, offKey: `${k}.beam.b4.off`, onKey: `${k}.beam.b4.on` },
      { bit: 5, offKey: `${k}.beam.b5.off`, onKey: `${k}.beam.b5.on` },
      { bit: 6, offKey: `${k}.beam.b6.off`, onKey: `${k}.beam.b6.on` },
      { bit: 7, offKey: `${k}.beam.b7.off`, onKey: `${k}.beam.b7.on` },
    ],
  }),
  item(120, {
    descriptionKey: `${k}.cv120.description`,
    hintKey: `${k}.cv120.hint`,
    kind: "bits",
    default: 0,
    bits: [
      { bit: 0, offKey: `${k}.beam.b0.off`, onKey: `${k}.beam.b0.on` },
      { bit: 1, offKey: `${k}.beam.b1.off`, onKey: `${k}.beam.b1.on` },
      { bit: 2, offKey: `${k}.beam.b2.off`, onKey: `${k}.beam.b2.on` },
      { bit: 3, offKey: `${k}.beam.b3.off`, onKey: `${k}.beam.b3.on` },
      { bit: 4, offKey: `${k}.beam.b4.off`, onKey: `${k}.beam.b4.on` },
      { bit: 5, offKey: `${k}.beam.b5.off`, onKey: `${k}.beam.b5.on` },
      { bit: 6, offKey: `${k}.beam.b6.off`, onKey: `${k}.beam.b6.on` },
      { bit: 7, offKey: `${k}.beam.b7.off`, onKey: `${k}.beam.b7.on` },
    ],
  }),
  item(123, {
    descriptionKey: `${k}.cv123.description`,
    hintKey: `${k}.cv123.hint`,
    min: 0,
    max: 99,
    default: 0,
  }),
  item(124, {
    descriptionKey: `${k}.cv124.description`,
    hintKey: `${k}.cv124.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(125, {
    descriptionKey: `${k}.effectHl.description`,
    ...effectExtra,
  }),
  item(126, {
    descriptionKey: `${k}.effectRl.description`,
    ...effectExtra,
  }),
  ...numbered([127, 128, 129, 130, 131, 132], `${k}.effectFo.description`, effectExtra, 1),
  item(133, {
    descriptionKey: `${k}.cv133.description`,
    hintKey: `${k}.cv133.hint`,
    kind: "bits",
    default: 0,
    bits: [{ bit: 0, offKey: `${k}.cv133.b0.off`, onKey: `${k}.cv133.b0.on` }],
  }),
  item(134, {
    descriptionKey: `${k}.cv134.description`,
    hintKey: `${k}.cv134.hint`,
    min: 1,
    max: 14,
    default: 6,
  }),
  item(137, {
    descriptionKey: `${k}.cv137.description`,
    hintKey: `${k}.cv137.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(138, {
    descriptionKey: `${k}.cv138.description`,
    hintKey: `${k}.cv138.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(139, {
    descriptionKey: `${k}.cv139.description`,
    hintKey: `${k}.cv139.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(140, {
    descriptionKey: `${k}.cv140.description`,
    hintKey: `${k}.cv140.hint`,
    kind: "enum",
    default: 0,
    options: [
      { value: 0, labelKey: `${k}.cv140.off` },
      { value: 1, labelKey: `${k}.cv140.auto` },
      { value: 2, labelKey: `${k}.cv140.manual` },
      { value: 3, labelKey: `${k}.cv140.both` },
      { value: 11, labelKey: `${k}.cv140.autoNow` },
      { value: 12, labelKey: `${k}.cv140.manualNow` },
      { value: 13, labelKey: `${k}.cv140.bothNow` },
    ],
  }),
  item(141, {
    descriptionKey: `${k}.cv141.description`,
    hintKey: `${k}.cv141.hint`,
    min: 0,
    max: 255,
    default: 20,
  }),
  item(143, {
    descriptionKey: `${k}.cv143.description`,
    hintKey: `${k}.cv143.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(144, {
    descriptionKey: `${k}.cv144.description`,
    hintKey: `${k}.cv144.hint`,
    kind: "bits",
    bits: [{ bit: 4, offKey: `${k}.cv144.b4.off`, onKey: `${k}.cv144.b4.on` }],
  }),
  item(146, {
    descriptionKey: `${k}.cv146.description`,
    hintKey: `${k}.cv146.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(147, {
    descriptionKey: `${k}.cv147.description`,
    hintKey: `${k}.cv147.hint`,
    min: 0,
    max: 255,
    default: 100,
  }),
  item(148, {
    descriptionKey: `${k}.cv148.description`,
    min: 0,
    max: 255,
    default: 100,
  }),
  item(149, {
    descriptionKey: `${k}.cv149.description`,
    min: 0,
    max: 255,
    default: 100,
  }),
  item(151, {
    descriptionKey: `${k}.cv151.description`,
    hintKey: `${k}.cv151.hint`,
    min: 0,
    max: 99,
    default: 0,
  }),
  item(152, {
    descriptionKey: `${k}.cv152.description`,
    hintKey: `${k}.cv152.hint`,
    kind: "bits",
    default: 0,
    bits: [
      { bit: 0, offKey: `${k}.cv152.b0.off`, onKey: `${k}.cv152.b0.on` },
      { bit: 1, offKey: `${k}.cv152.b1.off`, onKey: `${k}.cv152.b1.on` },
      { bit: 2, offKey: `${k}.cv152.b2.off`, onKey: `${k}.cv152.b2.on` },
      { bit: 3, offKey: `${k}.cv152.b3.off`, onKey: `${k}.cv152.b3.on` },
      { bit: 4, offKey: `${k}.cv152.b4.off`, onKey: `${k}.cv152.b4.on` },
      { bit: 5, offKey: `${k}.cv152.b5.off`, onKey: `${k}.cv152.b5.on` },
      { bit: 6, offKey: `${k}.cv152.b6.off`, onKey: `${k}.cv152.b6.on` },
      { bit: 7, offKey: `${k}.cv152.b7.off`, onKey: `${k}.cv152.b7.on` },
    ],
  }),
  item(153, {
    descriptionKey: `${k}.cv153.description`,
    hintKey: `${k}.cv153.hint`,
    min: 0,
    max: 255,
    default: 100,
  }),
  item(155, {
    descriptionKey: `${k}.cv155.description`,
    hintKey: `${k}.cv155.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(156, {
    descriptionKey: `${k}.cv156.description`,
    hintKey: `${k}.cv156.hint`,
    min: 0,
    max: 158,
    default: 0,
  }),
  item(157, {
    descriptionKey: `${k}.cv157.description`,
    hintKey: `${k}.cv157.hint`,
    min: 0,
    max: 29,
    default: 0,
  }),
  ...numbered([159, 160], `${k}.effectFo.description`, effectExtra, 7),
  item(161, {
    descriptionKey: `${k}.cv161.description`,
    hintKey: `${k}.cv161.hint`,
    min: 0,
    max: 3,
    default: 0,
  }),
  item(162, {
    descriptionKey: `${k}.cv162.description`,
    hintKey: `${k}.cv162.hint`,
    min: 0,
    max: 255,
    default: 49,
  }),
  item(163, {
    descriptionKey: `${k}.cv163.description`,
    hintKey: `${k}.cv163.hint`,
    min: 0,
    max: 255,
    default: 205,
  }),
  item(164, {
    descriptionKey: `${k}.cv164.description`,
    hintKey: `${k}.cv164.hint`,
    min: 0,
    max: 255,
    default: 127,
  }),
  item(165, {
    descriptionKey: `${k}.cv165.description`,
    hintKey: `${k}.cv165.hint`,
    min: 0,
    max: 255,
    default: 30,
  }),
  item(179, {
    descriptionKey: `${k}.cv179.description`,
    hintKey: `${k}.cv179.hint`,
    min: 0,
    max: 255,
    default: 128,
  }),
  item(190, {
    descriptionKey: `${k}.cv190.description`,
    hintKey: `${k}.cv190.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(191, {
    descriptionKey: `${k}.cv191.description`,
    hintKey: `${k}.cv191.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(192, {
    descriptionKey: `${k}.cv192.description`,
    hintKey: `${k}.cv192.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(193, {
    descriptionKey: `${k}.cv193.description`,
    hintKey: `${k}.cv193.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(194, {
    descriptionKey: `${k}.cv194.description`,
    hintKey: `${k}.cv194.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  ...numbered([195, 196, 197, 198, 199, 200], `${k}.effectFo.description`, effectExtra, 9),
  item(201, {
    descriptionKey: `${k}.cv201.description`,
    hintKey: `${k}.cv201.hint`,
    kind: "enum",
    default: 0,
    options: [
      { value: 0, labelKey: `${k}.cv201.susi` },
      { value: 11, labelKey: `${k}.cv201.logic` },
      { value: 22, labelKey: `${k}.cv201.reed` },
      { value: 33, labelKey: `${k}.cv201.servo` },
      { value: 44, labelKey: `${k}.cv201.burst` },
      { value: 55, labelKey: `${k}.cv201.i2c` },
      { value: 66, labelKey: `${k}.cv201.compat` },
    ],
  }),
  item(202, {
    descriptionKey: `${k}.cv202.description`,
    hintKey: `${k}.cv202.hint`,
    min: 0,
    max: 66,
    default: 0,
  }),
  ...numbered([205, 206, 207], `${k}.effectFo.description`, effectExtra, 15),
  item(249, {
    descriptionKey: `${k}.cv249.description`,
    hintKey: `${k}.cv249.hint`,
    min: 0,
    max: 255,
    readOnly: true,
  }),
  item(266, {
    descriptionKey: `${k}.cv266.description`,
    hintKey: `${k}.cv266.hint`,
    min: 0,
    max: 255,
    default: 65,
  }),
  item(267, {
    descriptionKey: `${k}.cv267.description`,
    hintKey: `${k}.cv267.hint`,
    min: 0,
    max: 255,
    default: 63,
  }),
  item(268, {
    descriptionKey: `${k}.cv268.description`,
    hintKey: `${k}.cv268.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(269, {
    descriptionKey: `${k}.cv269.description`,
    hintKey: `${k}.cv269.hint`,
    min: 0,
    max: 255,
    default: 10,
  }),
  item(275, {
    descriptionKey: `${k}.cv275.description`,
    min: 0,
    max: 255,
    default: 220,
  }),
  item(276, {
    descriptionKey: `${k}.cv276.description`,
    min: 0,
    max: 255,
    default: 220,
  }),
  item(277, {
    descriptionKey: `${k}.cv277.description`,
    hintKey: `${k}.cv277.hint`,
    min: 0,
    max: 255,
    default: 10,
  }),
  item(281, {
    descriptionKey: `${k}.cv281.description`,
    min: 0,
    max: 255,
    default: 1,
  }),
  item(282, {
    descriptionKey: `${k}.cv282.description`,
    hintKey: `${k}.cv282.hint`,
    min: 0,
    max: 255,
    default: 30,
  }),
  item(283, {
    descriptionKey: `${k}.cv283.description`,
    min: 0,
    max: 255,
    default: 255,
  }),
  item(284, {
    descriptionKey: `${k}.cv284.description`,
    min: 0,
    max: 255,
    default: 1,
  }),
  item(285, {
    descriptionKey: `${k}.cv285.description`,
    hintKey: `${k}.cv285.hint`,
    min: 0,
    max: 255,
    default: 30,
  }),
  item(286, {
    descriptionKey: `${k}.cv286.description`,
    min: 0,
    max: 255,
    default: 20,
  }),
  item(287, {
    descriptionKey: `${k}.cv287.description`,
    hintKey: `${k}.cv287.hint`,
    min: 0,
    max: 255,
    default: 50,
  }),
  item(288, {
    descriptionKey: `${k}.cv288.description`,
    hintKey: `${k}.cv288.hint`,
    min: 0,
    max: 255,
    default: 50,
  }),
  item(308, {
    descriptionKey: `${k}.cv308.description`,
    hintKey: `${k}.cv308.hint`,
    min: 0,
    max: 28,
    default: 25,
  }),
  item(309, {
    descriptionKey: `${k}.cv309.description`,
    hintKey: `${k}.cv309.hint`,
    min: 0,
    max: 29,
    default: 0,
  }),
  item(310, {
    descriptionKey: `${k}.cv310.description`,
    hintKey: `${k}.cv310.hint`,
    min: 0,
    max: 255,
    default: 1,
  }),
  item(311, {
    descriptionKey: `${k}.cv311.description`,
    hintKey: `${k}.cv311.hint`,
    min: 0,
    max: 28,
    default: 0,
  }),
  item(312, {
    descriptionKey: `${k}.cv312.description`,
    hintKey: `${k}.cv312.hint`,
    min: 0,
    max: 28,
    default: 13,
  }),
  item(313, {
    descriptionKey: `${k}.cv313.description`,
    hintKey: `${k}.cv313.hint`,
    min: 0,
    max: 128,
    default: 114,
  }),
  item(314, {
    descriptionKey: `${k}.cv314.description`,
    hintKey: `${k}.cv314.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(349, {
    descriptionKey: `${k}.cv349.description`,
    hintKey: `${k}.cv349.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(351, {
    descriptionKey: `${k}.cv351.description`,
    hintKey: `${k}.cv351.hint`,
    min: 1,
    max: 255,
    default: 128,
  }),
  item(352, {
    descriptionKey: `${k}.cv352.description`,
    hintKey: `${k}.cv352.hint`,
    min: 1,
    max: 255,
    default: 255,
  }),
  item(353, {
    descriptionKey: `${k}.cv353.description`,
    hintKey: `${k}.cv353.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(355, {
    descriptionKey: `${k}.cv355.description`,
    hintKey: `${k}.cv355.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(376, {
    descriptionKey: `${k}.cv376.description`,
    hintKey: `${k}.cv376.hint`,
    min: 0,
    max: 255,
    default: 255,
  }),
  item(393, {
    descriptionKey: `${k}.cv393.description`,
    hintKey: `${k}.cv393.hint`,
    kind: "bits",
    bits: [
      { bit: 0, offKey: `${k}.cv393.b0.off`, onKey: `${k}.cv393.b0.on` },
      { bit: 1, offKey: `${k}.cv393.b1.off`, onKey: `${k}.cv393.b1.on` },
    ],
  }),
  item(394, {
    descriptionKey: `${k}.cv394.description`,
    hintKey: `${k}.cv394.hint`,
    kind: "bits",
    bits: [
      { bit: 0, offKey: `${k}.cv394.b0.off`, onKey: `${k}.cv394.b0.on` },
      { bit: 4, offKey: `${k}.cv394.b4.off`, onKey: `${k}.cv394.b4.on` },
      { bit: 6, offKey: `${k}.cv394.b6.off`, onKey: `${k}.cv394.b6.on` },
    ],
  }),
  item(395, {
    descriptionKey: `${k}.cv395.description`,
    hintKey: `${k}.cv395.hint`,
    min: 0,
    max: 255,
    default: 64,
  }),
  item(396, {
    descriptionKey: `${k}.cv396.description`,
    hintKey: `${k}.cv396.hint`,
    min: 0,
    max: 29,
    default: 0,
  }),
  item(397, {
    descriptionKey: `${k}.cv397.description`,
    hintKey: `${k}.cv397.hint`,
    min: 0,
    max: 29,
    default: 0,
  }),
  ...grouped(
    `${k}.groups.inputs`,
    numbered(
      Array.from({ length: 29 }, (_, i) => 400 + i),
      `${k}.inputMap.description`,
      { hintKey: `${k}.inputMap.hint`, min: 0, max: 255, default: 0 },
      0,
    ),
  ),
  ...grouped(`${k}.groups.swiss`, swissMapping),
  ...grouped(
    `${k}.groups.swiss`,
    numbered(
      [508, 509, 510, 511, 512],
      `${k}.swissDim.description`,
      { hintKey: `${k}.swissDim.hint`, min: 0, max: 255, default: 0 },
    ),
  ),
  ...grouped(`${k}.groups.functionSounds`, [
    ...functionSounds,
    item(573, { descriptionKey: `${k}.classSample.simmer`, min: 0, max: 255 }),
    item(574, { descriptionKey: `${k}.cv574.description`, min: 0, max: 255, default: 0 }),
    item(575, { descriptionKey: `${k}.classSample.direction`, min: 0, max: 255 }),
    item(576, { descriptionKey: `${k}.cv576.description`, min: 0, max: 255, default: 0 }),
    item(577, { descriptionKey: `${k}.classSample.brake`, min: 0, max: 255 }),
    item(578, { descriptionKey: `${k}.cv578.description`, min: 0, max: 255, default: 0 }),
    item(579, { descriptionKey: `${k}.classSample.thyristor`, min: 0, max: 255 }),
    item(580, { descriptionKey: `${k}.cv580.description`, min: 0, max: 255, default: 0 }),
    item(581, { descriptionKey: `${k}.classSample.startWhistle`, min: 0, max: 255 }),
    item(582, { descriptionKey: `${k}.cv582.description`, min: 0, max: 255, default: 0 }),
    item(583, { descriptionKey: `${k}.classSample.blowoff`, min: 0, max: 255 }),
    item(584, { descriptionKey: `${k}.cv584.description`, min: 0, max: 255, default: 0 }),
    item(585, { descriptionKey: `${k}.classSample.emotor`, min: 0, max: 255 }),
    item(586, { descriptionKey: `${k}.cv586.description`, min: 0, max: 255, default: 0 }),
    item(587, { descriptionKey: `${k}.classSample.rolling`, min: 0, max: 255 }),
    item(588, { descriptionKey: `${k}.cv588.description`, min: 0, max: 255, default: 0 }),
    item(589, { descriptionKey: `${k}.classSample.switchgear`, min: 0, max: 255 }),
    item(590, { descriptionKey: `${k}.cv590.description`, min: 0, max: 255, default: 0 }),
    item(592, { descriptionKey: `${k}.cv592.description`, hintKey: `${k}.cv592.hint`, min: 0, max: 255, default: 0 }),
    item(600, { descriptionKey: `${k}.cv600.description`, min: 0, max: 255, default: 0 }),
    item(602, { descriptionKey: `${k}.cv602.description`, min: 0, max: 255, default: 0 }),
    item(604, { descriptionKey: `${k}.cv604.description`, min: 0, max: 255, default: 0 }),
  ]),
  item(102, {
    descriptionKey: `${k}.cv102.description`,
    hintKey: `${k}.cv102.hint`,
    kind: "bits",
    bits: [{ bit: 0, offKey: `${k}.cv102.b0.off`, onKey: `${k}.cv102.b0.on` }],
  }),
  item(113, {
    descriptionKey: `${k}.cv113.description`,
    hintKey: `${k}.cv113.hint`,
    min: 0,
    max: 255,
  }),
  item(135, {
    descriptionKey: `${k}.cv135.description`,
    hintKey: `${k}.cv135.hint`,
    min: 0,
    max: 255,
  }),
  item(136, {
    descriptionKey: `${k}.cv136.description`,
    hintKey: `${k}.cv136.hint`,
    min: 0,
    max: 255,
    default: 128,
  }),
  item(154, {
    descriptionKey: `${k}.cv154.description`,
    hintKey: `${k}.cv154.hint`,
    kind: "bits",
    bits: [{ bit: 1, offKey: `${k}.cv154.b1.off`, onKey: `${k}.cv154.b1.on` }],
  }),
  item(158, {
    descriptionKey: `${k}.cv158.description`,
    hintKey: `${k}.cv158.hint`,
    kind: "bits",
    bits: [
      { bit: 1, offKey: `${k}.cv158.b1.off`, onKey: `${k}.cv158.b1.on` },
      { bit: 2, offKey: `${k}.cv158.b2.off`, onKey: `${k}.cv158.b2.on` },
      { bit: 7, offKey: `${k}.cv158.b7.off`, onKey: `${k}.cv158.b7.on` },
    ],
  }),
  ...servoN(2, 166),
  ...servoN(3, 170),
  ...servoN(4, 174),
  item(178, {
    descriptionKey: `${k}.cv178.description`,
    hintKey: `${k}.cv178.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  ...numbered(
    [181, 182, 183, 184],
    `${k}.servo.fn`,
    { hintKey: `${k}.servo.fnHint`, min: 0, max: 255, default: 0 },
  ),
  item(185, {
    descriptionKey: `${k}.cv185.description`,
    hintKey: `${k}.cv185.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  ...numbered(
    [186, 187, 188, 189],
    `${k}.panto.description`,
    { hintKey: `${k}.panto.hint`, min: 0, max: 255, default: 0 },
  ),
  item(203, {
    descriptionKey: `${k}.cv203.description`,
    hintKey: `${k}.cv203.hint`,
    min: 0,
    max: 66,
    default: 0,
  }),
  item(204, {
    descriptionKey: `${k}.cv204.description`,
    hintKey: `${k}.cv204.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(246, {
    descriptionKey: `${k}.cv246.description`,
    hintKey: `${k}.cv246.hint`,
    min: 0,
    max: 255,
  }),
  item(250, {
    descriptionKey: `${k}.cv250.description`,
    hintKey: `${k}.cv250.hint`,
    min: 0,
    max: 255,
    readOnly: true,
  }),
  item(251, {
    descriptionKey: `${k}.cv251.description`,
    hintKey: `${k}.cv251.hint`,
    min: 0,
    max: 255,
    readOnly: true,
  }),
  item(252, {
    descriptionKey: `${k}.cv252.description`,
    min: 0,
    max: 255,
    readOnly: true,
  }),
  item(253, {
    descriptionKey: `${k}.cv253.description`,
    hintKey: `${k}.cv253.hint`,
    min: 0,
    max: 255,
    readOnly: true,
  }),
  item(258, {
    descriptionKey: `${k}.cv258.description`,
    hintKey: `${k}.cv258.hint`,
    min: 0,
    max: 255,
    readOnly: true,
  }),
  item(259, {
    descriptionKey: `${k}.cv259.description`,
    hintKey: `${k}.cv259.hint`,
    min: 0,
    max: 255,
    readOnly: true,
  }),
  item(263, {
    descriptionKey: `${k}.cv263.description`,
    hintKey: `${k}.cv263.hint`,
    min: 0,
    max: 255,
  }),
  item(264, {
    descriptionKey: `${k}.cv264.description`,
    hintKey: `${k}.cv264.hint`,
    min: 10,
    max: 158,
    default: 15,
  }),
  item(265, {
    descriptionKey: `${k}.cv265.description`,
    hintKey: `${k}.cv265.hint`,
    min: 0,
    max: 255,
  }),
  item(271, {
    descriptionKey: `${k}.cv271.description`,
    hintKey: `${k}.cv271.hint`,
    min: 0,
    max: 255,
  }),
  item(272, {
    descriptionKey: `${k}.cv272.description`,
    hintKey: `${k}.cv272.hint`,
    min: 0,
    max: 255,
  }),
  item(273, {
    descriptionKey: `${k}.cv273.description`,
    hintKey: `${k}.cv273.hint`,
    min: 0,
    max: 255,
  }),
  item(274, {
    descriptionKey: `${k}.cv274.description`,
    hintKey: `${k}.cv274.hint`,
    min: 0,
    max: 255,
  }),
  item(278, {
    descriptionKey: `${k}.cv278.description`,
    hintKey: `${k}.cv278.hint`,
    min: 0,
    max: 255,
    default: 10,
  }),
  item(279, {
    descriptionKey: `${k}.cv279.description`,
    hintKey: `${k}.cv279.hint`,
    min: 0,
    max: 255,
    default: 1,
  }),
  item(280, {
    descriptionKey: `${k}.cv280.description`,
    hintKey: `${k}.cv280.hint`,
    min: 0,
    max: 255,
    default: 10,
  }),
  item(289, { descriptionKey: `${k}.cv289.description`, min: 0, max: 255 }),
  item(290, {
    descriptionKey: `${k}.cv290.description`,
    hintKey: `${k}.cv290.hint`,
    min: 0,
    max: 255,
    default: 50,
  }),
  item(291, { descriptionKey: `${k}.cv291.description`, min: 0, max: 255, default: 255 }),
  item(292, {
    descriptionKey: `${k}.cv292.description`,
    hintKey: `${k}.cv292.hint`,
    min: 0,
    max: 255,
    default: 128,
  }),
  item(293, { descriptionKey: `${k}.cv293.description`, min: 0, max: 255, default: 100 }),
  item(294, { descriptionKey: `${k}.cv294.description`, min: 0, max: 255 }),
  item(295, { descriptionKey: `${k}.cv295.description`, min: 0, max: 255 }),
  item(296, { descriptionKey: `${k}.cv296.description`, min: 0, max: 255, default: 0 }),
  item(297, {
    descriptionKey: `${k}.cv297.description`,
    hintKey: `${k}.cv297.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(298, {
    descriptionKey: `${k}.cv298.description`,
    hintKey: `${k}.cv298.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(299, {
    descriptionKey: `${k}.cv299.description`,
    hintKey: `${k}.cv299.hint`,
    min: 0,
    max: 100,
    default: 0,
  }),
  item(307, {
    descriptionKey: `${k}.cv307.description`,
    hintKey: `${k}.cv307.hint`,
    kind: "bits",
    bits: [
      { bit: 0, offKey: `${k}.cv307.b0.off`, onKey: `${k}.cv307.b0.on` },
      { bit: 1, offKey: `${k}.cv307.b1.off`, onKey: `${k}.cv307.b1.on` },
      { bit: 7, offKey: `${k}.cv307.b7.off`, onKey: `${k}.cv307.b7.on` },
    ],
  }),
  ...grouped(`${k}.groups.generators`, [
    ...randomInterval(1, 315, [1, 60, 5]),
    ...randomInterval(2, 320, [20, 80, 5]),
    ...randomInterval(3, 323, [30, 90, 3]),
  ]),
  item(339, {
    descriptionKey: `${k}.cv339.description`,
    hintKey: `${k}.cv339.hint`,
    min: 0,
    max: 28,
    default: 0,
  }),
  item(340, {
    descriptionKey: `${k}.cv340.description`,
    hintKey: `${k}.cv340.hint`,
    min: 0,
    max: 10,
    default: 0,
  }),
  ...grouped(
    `${k}.groups.inputs`,
    numbered(
      [341, 342, 343],
      `${k}.switchDur.description`,
      { hintKey: `${k}.switchDur.hint`, min: 0, max: 255, default: 0 },
    ),
  ),
  item(344, {
    descriptionKey: `${k}.cv344.description`,
    hintKey: `${k}.cv344.hint`,
    min: 0,
    max: 255,
  }),
  item(345, {
    descriptionKey: `${k}.cv345.description`,
    hintKey: `${k}.cv345.hint`,
    kind: "bits",
    default: 0,
    bits: [
      { bit: 0, offKey: `${k}.cv345.b0.off`, onKey: `${k}.cv345.b0.on` },
      { bit: 1, offKey: `${k}.cv345.b1.off`, onKey: `${k}.cv345.b1.on` },
      { bit: 2, offKey: `${k}.cv345.b2.off`, onKey: `${k}.cv345.b2.on` },
    ],
  }),
  item(346, { descriptionKey: `${k}.cv346.description`, min: 0, max: 255 }),
  item(347, {
    descriptionKey: `${k}.cv347.description`,
    hintKey: `${k}.cv347.hint`,
    min: 0,
    max: 28,
    default: 0,
  }),
  item(348, {
    descriptionKey: `${k}.cv348.description`,
    hintKey: `${k}.cv348.hint`,
    min: 0,
    max: 31,
    default: 0,
  }),
  item(350, {
    descriptionKey: `${k}.cv350.description`,
    hintKey: `${k}.cv350.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(354, {
    descriptionKey: `${k}.cv354.description`,
    hintKey: `${k}.cv354.hint`,
    min: 1,
    max: 255,
    default: 11,
  }),
  item(356, {
    descriptionKey: `${k}.cv356.description`,
    hintKey: `${k}.cv356.hint`,
    min: 0,
    max: 28,
  }),
  item(357, {
    descriptionKey: `${k}.cv357.description`,
    hintKey: `${k}.cv357.hint`,
    min: 0,
    max: 255,
  }),
  item(358, {
    descriptionKey: `${k}.cv358.description`,
    hintKey: `${k}.cv358.hint`,
    min: 0,
    max: 255,
  }),
  item(359, {
    descriptionKey: `${k}.cv359.description`,
    hintKey: `${k}.cv359.hint`,
    min: 0,
    max: 255,
    default: 30,
  }),
  item(360, {
    descriptionKey: `${k}.cv360.description`,
    hintKey: `${k}.cv360.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(361, {
    descriptionKey: `${k}.cv361.description`,
    hintKey: `${k}.cv361.hint`,
    min: 0,
    max: 255,
    default: 20,
  }),
  item(362, {
    descriptionKey: `${k}.cv362.description`,
    hintKey: `${k}.cv362.hint`,
    min: 0,
    max: 255,
  }),
  item(363, {
    descriptionKey: `${k}.cv363.description`,
    hintKey: `${k}.cv363.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(364, {
    descriptionKey: `${k}.cv364.description`,
    hintKey: `${k}.cv364.hint`,
    min: 0,
    max: 255,
  }),
  item(365, {
    descriptionKey: `${k}.cv365.description`,
    hintKey: `${k}.cv365.hint`,
    min: 0,
    max: 255,
  }),
  item(366, { descriptionKey: `${k}.cv366.description`, min: 0, max: 255, default: 48 }),
  item(367, {
    descriptionKey: `${k}.cv367.description`,
    hintKey: `${k}.cv367.hint`,
    min: 0,
    max: 255,
    default: 150,
  }),
  item(368, {
    descriptionKey: `${k}.cv368.description`,
    hintKey: `${k}.cv368.hint`,
    min: 0,
    max: 255,
    default: 100,
  }),
  item(369, {
    descriptionKey: `${k}.cv369.description`,
    hintKey: `${k}.cv369.hint`,
    min: 0,
    max: 255,
    default: 30,
  }),
  item(370, { descriptionKey: `${k}.cv370.description`, min: 0, max: 255, default: 25 }),
  item(371, { descriptionKey: `${k}.cv371.description`, min: 0, max: 255, default: 15 }),
  item(372, {
    descriptionKey: `${k}.cv372.description`,
    hintKey: `${k}.cv372.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(373, {
    descriptionKey: `${k}.cv373.description`,
    hintKey: `${k}.cv373.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(374, {
    descriptionKey: `${k}.cv374.description`,
    hintKey: `${k}.cv374.hint`,
    min: 0,
    max: 29,
    default: 0,
  }),
  item(375, {
    descriptionKey: `${k}.cv375.description`,
    hintKey: `${k}.cv375.hint`,
    min: 0,
    max: 10,
    default: 0,
  }),
  item(378, {
    descriptionKey: `${k}.cv378.description`,
    hintKey: `${k}.cv378.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(379, {
    descriptionKey: `${k}.cv379.description`,
    hintKey: `${k}.cv379.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(380, {
    descriptionKey: `${k}.cv380.description`,
    hintKey: `${k}.cv380.hint`,
    min: 0,
    max: 28,
    default: 0,
  }),
  item(381, {
    descriptionKey: `${k}.cv381.description`,
    hintKey: `${k}.cv381.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(382, {
    descriptionKey: `${k}.cv382.description`,
    hintKey: `${k}.cv382.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(383, {
    descriptionKey: `${k}.cv383.description`,
    hintKey: `${k}.cv383.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(384, {
    descriptionKey: `${k}.cv384.description`,
    hintKey: `${k}.cv384.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(385, {
    descriptionKey: `${k}.cv385.description`,
    hintKey: `${k}.cv385.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(386, {
    descriptionKey: `${k}.cv386.description`,
    hintKey: `${k}.cv386.hint`,
    min: 0,
    max: 15,
    default: 0,
  }),
  item(387, {
    descriptionKey: `${k}.cv387.description`,
    hintKey: `${k}.cv387.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(388, {
    descriptionKey: `${k}.cv388.description`,
    hintKey: `${k}.cv388.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(389, {
    descriptionKey: `${k}.cv389.description`,
    hintKey: `${k}.cv389.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(390, {
    descriptionKey: `${k}.cv390.description`,
    hintKey: `${k}.cv390.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(391, {
    descriptionKey: `${k}.cv391.description`,
    hintKey: `${k}.cv391.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  ...grouped(`${k}.groups.inputs`, [
    item(392, {
      descriptionKey: `${k}.cv392.description`,
      hintKey: `${k}.switchDur.hint`,
      min: 0,
      max: 255,
      default: 0,
    }),
    item(671, {
      descriptionKey: `${k}.reed.sample`,
      descriptionParams: { n: 4 },
      hintKey: `${k}.reed.sampleHint`,
      min: 0,
      max: 255,
      default: 0,
    }),
    item(672, {
      descriptionKey: `${k}.reed.vol`,
      descriptionParams: { n: 4 },
      hintKey: `${k}.reed.volHint`,
      min: 0,
      max: 255,
      default: 0,
    }),
  ]),
  item(398, {
    descriptionKey: `${k}.cv398.description`,
    hintKey: `${k}.cv398.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(399, {
    descriptionKey: `${k}.cv399.description`,
    hintKey: `${k}.cv399.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  ...grouped(
    `${k}.groups.connections`,
    Array.from({ length: 6 }, (_, i) => [
      item(726 + i * 2, {
        descriptionKey: `${k}.conn.sound`,
        descriptionParams: { n: i + 1 },
        hintKey: `${k}.conn.soundHint`,
        min: 0,
        max: 255,
        default: 0,
      }),
      item(727 + i * 2, {
        descriptionKey: `${k}.conn.fo`,
        descriptionParams: { n: i + 1 },
        hintKey: `${k}.conn.foHint`,
        min: 0,
        max: 255,
        default: 0,
      }),
    ]).flat(),
  ),
  ...grouped(
    `${k}.groups.inputs`,
    Array.from({ length: 3 }, (_, i) => [
      item(738 + i * 2, {
        descriptionKey: `${k}.reed.sample`,
        descriptionParams: { n: i + 1 },
        hintKey: `${k}.reed.sampleHint`,
        min: 0,
        max: 255,
      }),
      item(739 + i * 2, {
        descriptionKey: `${k}.reed.vol`,
        descriptionParams: { n: i + 1 },
        hintKey: `${k}.reed.volHint`,
        min: 0,
        max: 255,
        default: 0,
      }),
    ]).flat(),
  ),
  ...grouped(
    `${k}.groups.generators`,
    Array.from({ length: 8 }, (_, i) => randomSound(i + 1, 744 + i * 3)).flat(),
  ),
  item(768, {
    descriptionKey: `${k}.cv768.description`,
    hintKey: `${k}.cv768.hint`,
    min: 0,
    max: 255,
    readOnly: true,
  }),
  item(835, {
    descriptionKey: `${k}.cv835.description`,
    hintKey: `${k}.cv835.hint`,
    min: 0,
    max: 32,
  }),
  item(836, {
    descriptionKey: `${k}.cv836.description`,
    hintKey: `${k}.cv836.hint`,
    kind: "bits",
    bits: [{ bit: 0, offKey: `${k}.cv836.b0.off`, onKey: `${k}.cv836.b0.on` }],
  }),
  item(837, {
    descriptionKey: `${k}.cv837.description`,
    hintKey: `${k}.cv837.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(838, {
    descriptionKey: `${k}.cv838.description`,
    hintKey: `${k}.cv838.hint`,
    min: 0,
    max: 255,
    default: 255,
  }),
  item(839, {
    descriptionKey: `${k}.cv839.description`,
    hintKey: `${k}.cv839.hint`,
    min: 0,
    max: 255,
    readOnly: true,
  }),
  item(842, {
    descriptionKey: `${k}.cv842.description`,
    hintKey: `${k}.cv842.hint`,
    min: 0,
    max: 255,
    readOnly: true,
  }),
  item(843, {
    descriptionKey: `${k}.cv843.description`,
    hintKey: `${k}.cv843.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(844, {
    descriptionKey: `${k}.cv844.description`,
    hintKey: `${k}.cv844.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  ...grouped(
    `${k}.groups.scripts`,
    numbered(
      Array.from({ length: 40 }, (_, i) => 980 + i),
      `${k}.script.description`,
      { hintKey: `${k}.script.hint`, min: 0, max: 255 },
      980,
    ),
  ),
  item(830, {
    descriptionKey: `${k}.cv830.description`,
    hintKey: `${k}.cv830.hint`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(831, {
    descriptionKey: `${k}.cv831.description`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(832, {
    descriptionKey: `${k}.cv832.description`,
    min: 0,
    max: 255,
    default: 0,
  }),
  item(833, {
    descriptionKey: `${k}.cv833.description`,
    min: 0,
    max: 255,
    default: 0,
  }),
];

export const zimoMs450: DecoderProfile = {
  id: "zimo-ms450",
  features: ["cv", "speed", "address", "volume", "mapping"],
  cvs: [...zimoMs450Cvs].sort((a, b) => a.cv - b.cv),
};
